---
title: "DESeq"
author: "Max Alcer"
date: "2024-06-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(DESeq2)
library(Matrix)
library(tidyverse)
library(BiocParallel)
register(SnowParam(4))
```

# Load expression matrix and annotations
```{r}
RNA_expression_matrix <- readRDS("../data/pre_processed/RNA-Seq-filtered.rds")
RNA_expression_matrix <- RNA_expression_matrix + 1 # pseudocount
```

```{r}
RNA_annotations <- read_csv("../data/pre_processed/RNA_annotations.csv",show_col_types = FALSE)
```

# create DESeq2 object from expression matrix with design by sub trajectory
```{r}
dds <- DESeqDataSetFromMatrix(countData = RNA_expression_matrix,
                              colData = select(RNA_annotations, sample, Sub_trajectory_name),
                              design = ~ Sub_trajectory_name)
```

# perfrom differential gene expression analysis
```{r}
dea <- DESeq(dds, parallel = TRUE)
```

# save results related to two trajectory for MA Plot
```{r}
results <- results(dea, contrast = c("Sub_trajectory_name", 
                                     "Definitive erythroid trajectory", 
                                     "Megakaryocyte trajectory"))
```

```{r}
plotMA(results, colNonSig = "blue", colSig = "red")
```
```{r}
Sub_traj <- distinct(RNA_annotations, Sub_trajectory_name)$Sub_trajectory_name
```

# save results for all combinations of all sub trajectories 
```{r}
res_list <- list()
for(i in 1:(length(Sub_traj)-1)){
  for(j in (i+1):length(Sub_traj)){
    temp <- list(results(dea, contrast = c("Sub_trajectory_name",
                                           Sub_traj[i], 
                                           Sub_traj[j])))
    res_list <- append(res_list, temp)
  }
}
```

```{r}
combined_res <- do.call(rbind, lapply(res_list, function(x) {
  tibble(gene = rownames(x), padj = x$padj)
}))

combined_res <- combined_res %>% filter(padj != 0)

combined_res <- combined_res[order(combined_res$padj),]
```

```{r}
write_csv(combined_res, "genes_by_sig.csv")
```

# keep only the significant genes and each gene only once
```{r}
combined_res <- combined_res %>% 
  filter(padj <= 0.05) %>%
  distinct(gene, .keep_all = TRUE)

write_csv(combined_res, "genes_by_sig_unique.csv")
```







