---
title: "UMAP_RNA"
author: "Max Alcer"
date: "2024-06-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Matrix)
library(umap)
```

# Load expression matrix, annotations and DESeq2 results
```{r}
expression_matrix <- readRDS("../data/pre_processed/RNA-Seq-filtered.rds")
```

```{r}
annotations <- read_csv("../data/pre_processed/RNA_annotations.csv")
```

```{r}
DEG <- read_csv("../DESeq/genes_by_sig_RNA.csv")
```

# keep only the top 200 most significant genes
```{r}
DEG <- DEG %>% 
  filter(padj <= 0.05) %>%
  distinct(gene, keep_all = TRUE) %>%
  head(200)
```

```{r}
expression_matrix <- RNA_expression_matrix[DEG$gene,]
```

# perform UMAP with default or changed configurations
```{r}
custom.config <- umap.defaults
#custom.config$n_neighbors <- 5
#custom.config$min_dist <- 0.5
umap <- umap(t(expression_matrix), config = custom.config)
```

# transform results into a tibble and plot them
```{r}
umap <- tibble(umap_1 = umap$layout[,1], 
               umap_2 = umap$layout[,2], 
               Celltype = annotations$Sub_trajectory_name)
```

```{r}
ggplot(umap, aes(x = umap_1, y = umap_2, color = Celltype)) +
  geom_point()
ggsave("plots/UMAP_RNA_200.png")
```

